dist: bionic
language: python

python:
  - '3.8'

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest

branches:
  only:
    - staging
    
install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers --path /usr/local/bin

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test -v
